//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantOrder.GUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RestaurantOrder.GUI.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear order.
        /// </summary>
        internal static string ClearOrder {
            get {
                return ResourceManager.GetString("ClearOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to clear the order?.
        /// </summary>
        internal static string DoYouWantToClearOrder {
            get {
                return ResourceManager.GetString("DoYouWantToClearOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to save and send the order to {0}?.
        /// </summary>
        internal static string DoYouWantToSenOrder {
            get {
                return ResourceManager.GetString("DoYouWantToSenOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send mail.
        /// </summary>
        internal static string EmailSend {
            get {
                return ResourceManager.GetString("EmailSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email faild. Check configuration..
        /// </summary>
        internal static string EmailSendFaild {
            get {
                return ResourceManager.GetString("EmailSendFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order details.
        /// </summary>
        internal static string OrderDetails {
            get {
                return ResourceManager.GetString("OrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order details no data.
        /// </summary>
        internal static string OrderDetailsFaild {
            get {
                return ResourceManager.GetString("OrderDetailsFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order faild. Bad format email address..
        /// </summary>
        internal static string OrderFaild {
            get {
                return ResourceManager.GetString("OrderFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order completed seccesfully.
        /// </summary>
        internal static string OrderSuccess {
            get {
                return ResourceManager.GetString("OrderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save order.
        /// </summary>
        internal static string SaveOrder {
            get {
                return ResourceManager.GetString("SaveOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error save order.
        /// </summary>
        internal static string SaveOrderError {
            get {
                return ResourceManager.GetString("SaveOrderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send order.
        /// </summary>
        internal static string SendOrder {
            get {
                return ResourceManager.GetString("SendOrder", resourceCulture);
            }
        }
    }
}
